<?php
// Include all necessary configuration and helper files
require_once __DIR__ . '/../config/config.php';
require_once __DIR__ . '/../includes/db.php';
require_once __DIR__ . '/../includes/helpers.php';
require_once __DIR__ . '/../includes/permissions.php';
require_once __DIR__ . '/../auth/gmail_oauth.php';

// Check if user has admin permissions
if (!GmailOAuth::isValidAdminSession()) {
    redirect('../auth/admin_login.php');
}

$user = get_logged_in_user();
$db = db();

// Handle report generation
if (isset($_GET['report_type'])) {
    $report_type = sanitize_input($_GET['report_type']);
    $format = sanitize_input($_GET['format'] ?? 'excel'); // Default to Excel for downloads

    // Optional filters
    $sub_county_id = isset($_GET['sub_county_id']) ? (int)$_GET['sub_county_id'] : null;

    // Build SQL with optional sub_county filter
    $sql = "
        SELECT 
            t.name AS team_name,
            t.status AS team_status,
            sc.name AS sub_county_name,
            w.name AS ward_name,
            COUNT(p.id) AS player_count,
            CONCAT(u.first_name, ' ', u.last_name) AS coach_name
        FROM teams t
        LEFT JOIN wards w ON t.ward_id = w.id
        LEFT JOIN sub_counties sc ON w.sub_county_id = sc.id
        LEFT JOIN players p ON p.team_id = t.id
        LEFT JOIN users u ON u.id = t.coach_id
        
        WHERE (:sub_county_id IS NULL OR w.sub_county_id = :sub_county_id)
        GROUP BY t.id
        ORDER BY sub_county_name, team_name
    ";

    $report_data = $db->fetchAll($sql, ['sub_county_id' => $sub_county_id]);

    // Start report generation based on format
    if ($format === 'pdf') {
        // Generate HTML for PDF
        $html = '<!DOCTYPE html>
        <html>
        <head>
            <title>Teams Report - ' . date('Y-m-d') . '</title>
            <style>
                body { font-family: Arial, sans-serif; font-size: 12px; }
                h1 { color: #2c3e50; text-align: center; margin-bottom: 20px; }
                .header { margin-bottom: 20px; }
                .logo { text-align: center; margin-bottom: 15px; }
                .report-title { text-align: center; font-size: 18px; font-weight: bold; margin-bottom: 10px; }
                .report-date { text-align: center; color: #7f8c8d; margin-bottom: 20px; }
                table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
                th { background-color: #2c3e50; color: white; padding: 8px; text-align: left; }
                td { padding: 8px; border-bottom: 1px solid #ddd; }
                tr:nth-child(even) { background-color: #f2f2f2; }
                .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #7f8c8d; }
            </style>
        </head>
        <body>
            <div class="header">
                <div class="logo">
                    <img src="https://governorwavinyacup.com/wavinyacup/assets/images/logo.png" alt="Logo" style="height: 60px;">
                </div>
                <div class="report-title">Teams Report' . ($sub_county_id ? ' - ' . htmlspecialchars($db->fetchCell("SELECT name FROM sub_counties WHERE id = :id", ['id'=>$sub_county_id]) ?? '', ENT_QUOTES, 'UTF-8') : '') . '</div>
                <div class="report-date">Generated on: ' . date('F j, Y, g:i a') . '</div>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Team Name</th>
                        <th>Sub-County</th>
                        <th>Ward</th>
                        <th>Players</th>
                        <th>Coach</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>';

        // Add data rows
        $count = 1;
        foreach ($report_data as $row) {
            $html .= '<tr>';
            $html .= '<td>' . $count++ . '</td>';
            $html .= '<td>' . htmlspecialchars($row['team_name'] ?? '', ENT_QUOTES, 'UTF-8') . '</td>';
            $html .= '<td>' . htmlspecialchars($row['sub_county_name'] ?? '', ENT_QUOTES, 'UTF-8') . '</td>';
            $html .= '<td>' . htmlspecialchars($row['ward_name'] ?? '', ENT_QUOTES, 'UTF-8') . '</td>';
            $html .= '<td>' . (isset($row['player_count']) ? (int)$row['player_count'] : 0) . '</td>';
            $html .= '<td>' . htmlspecialchars($row['coach_name'] ?? '', ENT_QUOTES, 'UTF-8') . '</td>';
            $html .= '<td>' . htmlspecialchars(isset($row['team_status']) ? ucfirst((string)$row['team_status']) : '', ENT_QUOTES, 'UTF-8') . '</td>';
            $html .= '</tr>';
        }

        $html .= '</tbody></table>
            <div class="footer">
                <p>Governor Wavinya Cup - ' . date('Y') . ' | Generated by ' . $_SERVER['HTTP_HOST'] . '</p>
            </div>
        </body>
        </html>';

        // Prefer local mPDF if available
        $usedLocalPdf = false;
        $vendorAutoload = dirname(__DIR__) . '/vendor/autoload.php';
        if (file_exists($vendorAutoload)) {
            require_once $vendorAutoload;
        }
        if (class_exists('Mpdf\\Mpdf')) {
            try {
                $tmpDir = dirname(__DIR__) . '/tmp';
                if (!is_dir($tmpDir)) { @mkdir($tmpDir, 0775, true); }
                $mpdf = new Mpdf\\Mpdf(['tempDir' => $tmpDir]);
                $mpdf->WriteHTML($html);
                if (ob_get_level()) { ob_end_clean(); }
                header('Content-Type: application/pdf');
                header('Content-Disposition: attachment; filename="teams_report_' . date('Ymd_His') . '.pdf"');
                echo $mpdf->Output('', 'S'); // output as string to flush via echo
                $usedLocalPdf = true;
                exit;
            } catch (Throwable $e) {
                // fall back to external service
            }
        }

        // Use an external HTML to PDF conversion service as fallback
        $api_url = 'https://api.html2pdf.app/v1/generate';
        // Prefer environment variable if set; otherwise use provided key
        $api_key = getenv('HTML2PDF_API_KEY') ?: 'N3N3qIRvWFhGyLFYIS6YEHq60RgbNYTmus3ITyXplmjbyryRWsh2CuGEA8xpUuG8';
        
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $api_url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POST, true);
        // Timeouts for shared hosting reliability
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 10);
        curl_setopt($ch, CURLOPT_TIMEOUT, 25);
        // Allow temporarily disabling SSL verify via env flag if host has outdated CA bundle
        $disableVerify = getenv('HTML2PDF_DISABLE_SSL_VERIFY') === '1';
        if ($disableVerify) {
            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
            curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        }
        curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query([
            'html' => $html,
            'apiKey' => $api_key,
            'filename' => 'teams_report_' . date('Ymd_His') . '.pdf'
        ]));
        
        $response = curl_exec($ch);
        $httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $curlErr = curl_error($ch);
        curl_close($ch);
        
        if ($httpcode === 200 && $response !== false) {
            // Set headers for a proper PDF download
            if (ob_get_level()) { ob_end_clean(); }
            header('Content-Type: application/pdf');
            header('Content-Disposition: attachment; filename="teams_report_' . date('Ymd_His') . '.pdf"');
            echo $response; // PDF binary
        } else {
            // Log failure details for debugging
            try {
                $logsDir = dirname(__DIR__) . '/logs';
                if (!is_dir($logsDir)) { @mkdir($logsDir, 0775, true); }
                $logFile = $logsDir . '/pdf_generation.log';
                $snippet = is_string($response) ? substr($response, 0, 500) : '';
                $logLine = sprintf("[%s] HTML2PDF failed. HTTP=%s CURL_ERR=%s SNIPPET=%s\n", date('Y-m-d H:i:s'), (string)$httpcode, $curlErr ?: 'none', $snippet);
                @file_put_contents($logFile, $logLine, FILE_APPEND);
            } catch (Throwable $e) { /* ignore logging failures */ }

            // If debug flag is set, show details in plain text (no download)
            if (!empty($_GET['debug_pdf'])) {
                if (ob_get_level()) { ob_end_clean(); }
                header('Content-Type: text/plain; charset=UTF-8');
                echo "PDF generation failed.\n";
                echo "HTTP Code: " . ($httpcode ?: 'n/a') . "\n";
                echo "cURL Error: " . ($curlErr ?: 'none') . "\n";
                $snippet = is_string($response) ? substr($response, 0, 1000) : '';
                echo "Response snippet:\n" . $snippet . "\n\n";
                echo "Tips:\n- Ensure outbound HTTPS requests are allowed on the server.\n- If SSL verification issues occur, set env HTML2PDF_DISABLE_SSL_VERIFY=1 temporarily.\n- Verify API key and quota at https://html2pdf.app/\n";
                exit;
            }
            // Fallback to HTML download if PDF generation fails
            if (ob_get_level()) { ob_end_clean(); }
            header('Content-Type: text/html');
            header('Content-Disposition: attachment; filename="teams_report_' . date('Ymd_His') . '.html"');
            echo $html;
        }
        exit;
    }

    if ($format === 'excel') {
        // Set headers for a proper CSV file that Excel can open
        header('Content-Type: text/csv');
        header('Content-Disposition: attachment; filename="teams_report_' . date('Ymd_His') . '.csv"');
        header('Pragma: no-cache');
        header('Expires: 0');

        $output = fopen('php://output', 'w');

        // Output the header row
        fputcsv($output, ['Team Name', 'Sub-County', 'Ward', 'Player Count', 'Coach Name', 'Status']);
        
        // Output the data rows
        foreach ($report_data as $row) {
            fputcsv($output, [
                $row['team_name'],
                $row['sub_county_name'],
                $row['ward_name'],
                $row['player_count'],
                $row['coach_name'],
                $row['team_status']
            ]);
        }
        fclose($output);
        exit; // Important: Stop the script after sending the file
    }
}

// Get statistics for the dashboard view
$total_teams = $db->fetchRow("SELECT COUNT(*) as count FROM teams WHERE status = 'active'")['count'] ?? 0;
$total_players = $db->fetchRow("SELECT COUNT(*) as count FROM players WHERE is_active = 1")['count'] ?? 0;
$total_coaches = $db->fetchRow("SELECT COUNT(*) as count FROM users WHERE role = 'coach' AND is_active = 1")['count'] ?? 0;
$pending_registrations = $db->fetchRow("SELECT COUNT(*) as count FROM team_registrations WHERE status = 'pending'")['count'] ?? 0;

// Get teams by sub-county for the chart
$teams_by_sub_county = $db->fetchAll("
    SELECT sc.name as sub_county, COUNT(t.id) as team_count 
    FROM sub_counties sc 
    LEFT JOIN wards w ON sc.id = w.sub_county_id 
    LEFT JOIN teams t ON w.id = t.ward_id AND t.status = 'active' 
    GROUP BY sc.id, sc.name 
    ORDER BY team_count DESC
");

// Load all sub-counties for filter UI
$all_sub_counties = $db->fetchAll("SELECT id, name FROM sub_counties ORDER BY name");
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php $page_title = 'Reports'; include dirname(__DIR__) . '/includes/head.php'; ?>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        .sidebar {
            min-height: 100vh;
            background: linear-gradient(135deg, #0d47a1, #b71c1c);
        }
        .sidebar .nav-link {
            color: rgba(255, 255, 255, 0.8);
            padding: 12px 20px;
            border-radius: 8px;
            margin: 2px 0;
        }
        .sidebar .nav-link:hover,
        .sidebar .nav-link.active {
            color: white;
            background: rgba(255, 255, 255, 0.1);
        }
        .main-content {
            background: #f8f9fa;
            min-height: 100vh;
        }
    </style>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3 col-lg-2 px-0">
            <div class="sidebar p-3">
                <div class="text-center mb-4">
                    <img src="../assets/images/logo.png" alt="Governor Wavinya Cup 3rd Edition Logo" style="width: 120px; height: auto;" class="mb-2">
                    <h5 class="text-white mb-0">Governor Wavinya Cup 3rd Edition</h5>
                    <small class="text-white-50">Admin Dashboard</small>
                </div>

                <nav class="nav flex-column">
                    <a class="nav-link" href="dashboard.php">
                        <i class="fas fa-tachometer-alt me-2"></i>Dashboard
                    </a>
                    <a class="nav-link" href="teams.php">
                        <i class="fas fa-users me-2"></i>Teams
                    </a>
                    <a class="nav-link" href="players.php">
                        <i class="fas fa-user me-2"></i>Players
                    </a>
                    <a class="nav-link" href="coaches.php">
                        <i class="fas fa-chalkboard-teacher me-2"></i>Coaches
                    </a>
                    <a class="nav-link" href="registrations.php">
                        <i class="fas fa-clipboard-list me-2"></i>Registrations
                    </a>
                    <a class="nav-link active" href="reports.php">
                        <i class="fas fa-chart-bar me-2"></i>Reports
                    </a>
                    <a class="nav-link" href="settings.php">
                        <i class="fas fa-cog me-2"></i>Settings
                    </a>
                    <hr class="text-white-50">
                    <a class="nav-link" href="../auth/logout.php">
                        <i class="fas fa-sign-out-alt me-2"></i>Logout
                    </a>
                </nav>
            </div>
        </div>

        <div class="col-md-9 col-lg-10">
            <div class="main-content p-4">
                <div class="d-flex justify-content-between align-items-center mb-4">
                    <div>
                        <h2><i class="fas fa-chart-bar me-2"></i>Reports & Analytics</h2>
                        <p class="text-muted">View system statistics and generate reports</p>
                    </div>
                    <a href="?report_type=teams&format=excel" class="btn btn-primary">
                        <i class="fas fa-download me-2"></i>Export Full Report
                    </a>
                </div>

                <div class="row mb-4">
                    <div class="col-md-3">
                        <div class="card bg-primary text-white">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <div>
                                        <h3 class="mb-0"><?php echo $total_teams; ?></h3>
                                        <p class="mb-0">Active Teams</p>
                                    </div>
                                    <div class="align-self-center">
                                        <i class="fas fa-users fa-2x"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card bg-success text-white">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <div>
                                        <h3 class="mb-0"><?php echo $total_players; ?></h3>
                                        <p class="mb-0">Registered Players</p>
                                    </div>
                                    <div class="align-self-center">
                                        <i class="fas fa-user fa-2x"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card bg-warning text-white">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <div>
                                        <h3 class="mb-0"><?php echo $total_coaches; ?></h3>
                                        <p class="mb-0">Coaches</p>
                                    </div>
                                    <div class="align-self-center">
                                        <i class="fas fa-chalkboard-teacher fa-2x"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card bg-info text-white">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <div>
                                        <h3 class="mb-0"><?php echo $pending_registrations; ?></h3>
                                        <p class="mb-0">Pending Approvals</p>
                                    </div>
                                    <div class="align-self-center">
                                        <i class="fas fa-clock fa-2x"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header">
                                <h5 class="card-title mb-0">
                                    <i class="fas fa-chart-bar me-2"></i>Teams by Sub-County
                                </h5>
                            </div>
                            <div class="card-body">
                                <canvas id="teamsChart" height="100"></canvas>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card mb-3">
                            <div class="card-header">
                                <h5 class="card-title mb-0">
                                    <i class="fas fa-filter me-2"></i>Report Filter
                                </h5>
                            </div>
                            <div class="card-body">
                                <form method="get" class="row g-2">
                                    <input type="hidden" name="report_type" value="teams">
                                    <div class="col-12">
                                        <label for="subCountySelect" class="form-label">Sub-County</label>
                                        <select id="subCountySelect" name="sub_county_id" class="form-select">
                                            <option value="">All Sub-Counties</option>
                                            <?php foreach ($all_sub_counties as $sc): ?>
                                                <option value="<?php echo (int)$sc['id']; ?>" <?php echo ($sub_county_id && (int)$sub_county_id === (int)$sc['id']) ? 'selected' : ''; ?>>
                                                    <?php echo htmlspecialchars($sc['name'], ENT_QUOTES, 'UTF-8'); ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                    <div class="col-12 d-grid">
                                        <button class="btn btn-primary" type="submit">Apply Filter</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-header">
                                <h5 class="card-title mb-0">
                                    <i class="fas fa-list me-2"></i>Quick Actions
                                </h5>
                            </div>
                            <div class="card-body">
                                <div class="d-grid gap-2">
                                    <a href="?report_type=teams&format=pdf<?php echo $sub_county_id ? '&sub_county_id=' . (int)$sub_county_id : ''; ?>" class="btn btn-outline-primary">
                                        <i class="fas fa-file-pdf me-2"></i>Generate PDF Report
                                    </a>
                                    <a href="?report_type=teams&format=excel<?php echo $sub_county_id ? '&sub_county_id=' . (int)$sub_county_id : ''; ?>" class="btn btn-outline-success">
                                        <i class="fas fa-file-excel me-2"></i>Export to Excel
                                    </a>
                                    <a href="?report_type=analytics&format=json" class="btn btn-outline-info">
                                        <i class="fas fa-chart-pie me-2"></i>Detailed Analytics
                                    </a>
                                    <a href="?report_type=monthly&format=excel" class="btn btn-outline-warning">
                                        <i class="fas fa-calendar me-2"></i>Monthly Report
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script>
    // Teams by Sub-County Chart
    const ctx = document.getElementById('teamsChart').getContext('2d');
    new Chart(ctx, {
        type: 'bar',
        data: {
            labels: <?php echo json_encode(array_column($teams_by_sub_county, 'sub_county')); ?>,
            datasets: [{
                label: 'Number of Teams',
                data: <?php echo json_encode(array_column($teams_by_sub_county, 'team_count')); ?>,
                backgroundColor: 'rgba(13, 71, 161, 0.8)',
                borderColor: 'rgba(13, 71, 161, 1)',
                borderWidth: 1
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            scales: {
                y: {
                    beginAtZero: true,
                    ticks: {
                        stepSize: 1
                    }
                }
            }
        }
    });
</script>
</body>
</html>